use std::path::PathBuf;

use clap::{Args, Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(name = "nf-source")]
#[command(about = "Source pipeline tools for NextFrame")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    Download(DownloadArgs),
    Transcribe(TranscribeArgs),
    Align(AlignArgs),
    Cut(CutArgs),
    Preview(PreviewArgs),
}

#[derive(Debug, Args)]
pub struct DownloadArgs {
    #[arg(long)]
    pub url: String,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value_t = 1080)]
    pub format_height: u16,
}

#[derive(Debug, Args)]
pub struct TranscribeArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value = "large-v3")]
    pub model: String,
    #[arg(long, default_value = "en")]
    pub language: String,
    #[arg(long, default_value_t = 1)]
    pub jobs: usize,
}

#[derive(Debug, Args)]
pub struct AlignArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub srt_path: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value = "auto")]
    pub language: String,
}

#[derive(Debug, Args)]
pub struct CutArgs {
    #[arg(long)]
    pub video: PathBuf,
    #[arg(long)]
    pub sentences_path: PathBuf,
    #[arg(long)]
    pub plan_path: PathBuf,
    #[arg(long)]
    pub out_dir: PathBuf,
    #[arg(long, default_value_t = 0.0)]
    pub margin_sec: f64,
}

#[derive(Debug, Args)]
pub struct PreviewArgs {
    #[arg(long)]
    pub sentences_path: PathBuf,
    #[arg(long)]
    pub cut_report_path: PathBuf,
    #[arg(long)]
    pub out_path: PathBuf,
    #[arg(long, default_value = "NextFrame Source Preview")]
    pub title: String,
    #[arg(long, default_value = "Generated by nf-source preview")]
    pub subtitle: String,
    #[arg(long, default_value = "#f97316")]
    pub accent: String,
    #[arg(long, default_value = "sunrise")]
    pub theme: String,
}
